### ISSUE TITLE
Forallx SL: negation-elim?

### ISSUE THREAD

**Issue by loighic** [Carnap/Carnap#124] opened 2020-07-06 17:21 UTC
Have the procedures for using the ~E and ~I rules in ForallxSL and ForallxSLPlus changed? Last spring this worked: http://loighic.net/temp/10.5a but now I'm unable to successfully use ~E (e.g., http://loighic.net/temp/10.5b) and similarly with other problems. (I hope I'm not overlooking something obvious, in which case I apologize.)

Also, while we're on the subject, how easy is it to create new systems of rules? I'm using a selection of rules from ForallxSL and ForallxSLPlus, which mostly works fine, although there are a couple of problems that could be avoided with a system specific to my version of Forallx.

**Comment by gleachkr** [comment] 2020-07-06 17:47
Huh, that's odd.  There have been some changes to how assumptions get checked in ForallxSL since last spring that might conceivably be causing this, but I'm not yet able to reproduce the problem. The following proof seems to check out for me, in ForallxSL:

    ~(P/\~Q):PR
      P :AS
        ~Q:AS
        P&~Q:&I 2,3
        ~(P&~Q):R 1
      Q :~E 3-5
    P->Q :->I 2-6

Could you copy-paste the exact text of the proof from 10.5b, and the exact pandoc used in setting up the problem? Also, what shows up when you mouse over the `?` near the use of `~E`?

**Comment by loighic** [comment] 2020-07-06 17:59
Hmm, copying and pasting your proof here produces the same issue:

% ~~~{.Playground .ForallxSLPlus options="fonts tabindent render" guides="fitch"} 
% ~~~

But anyway, the error message is "Error on line 6: Some of the assumptions in the cited subproofs are not of the right form for this rule." And this is my proof and the code for the problem:

~~~{.Playground .ForallxSLPlus options="fonts tabindent render" guides="fitch"} 
~(P & ~Q)    :PR
    P    :AS
        ~Q    :AS
        P & ~Q    :&I 2,3
        ~(P & ~Q)    :R 1
    Q    :~E 3-5
P -> Q    :->I 2-6
~~~

% ~~~{.ProofChecker .ForallxSLPlus options="fonts tabindent render" guides="fitch" points="2"}
% 10.5 ~(P & ~Q) :|-:  P -> Q 
% ~~~

I should also add that, since I'm not teaching, this is not a pressing problem for me right now. 

(Without the '%' before each line of code.)

**Comment by gleachkr** [comment] 2020-07-06 18:14
OK. Yes, that's the error you'd expect if this had something to do with those recent changes. I've been able to reproduce the problem - for me it seems to be specific to ForallxSLPlus. Your proof checks out (for me) using the playground at  https://carnap.io/shared/gleachkr@gmail.com/carnap-forallx.pandoc.

I think I can see what the issue is. I'll push a fix. If I'm wrong that this is only an issue in ForallxSLPlus, please let me know!

**Comment by gleachkr** [comment] 2020-07-06 18:15
Also - double thanks for a helpful bug report when you're not even teaching! I appreciate it.

**Comment by loighic** [comment] 2020-07-06 18:18
Ok, yes, I was just checking the difference between ForallSLPlus and ForallSL, and the problem doesn't arise with the latter. (That didn't occur to me initially.)

**Comment by gleachkr** [comment] 2020-07-06 18:58
OK, should now be fixed!

**Closed as completed** 2020-07-06 18:58 UTC

**Comment by loighic** [comment] 2020-07-06 19:23
Works. Great. Thanks!

(And no problem. Seems like I'm always working, and fooling around with Forallx and Carnap is a little easier than what I'm supposed to be doing.)

**Comment by gleachkr** [comment] 2020-07-06 19:25
Ha! Yes, I know exactly what you mean.
