### ISSUE TITLE
Customizable points for late correct submissions

### ISSUE THREAD

**Issue by dsanson** [Carnap/Carnap#137] opened 2020-07-19 16:44 UTC
In the dashboard docs, you mention:

> Submitted problems received on time receive 5 points each, and late submissions receive 2 points each. Both the point amount awarded for a given problem and the treatment of late problems are likely to become customizable in the future.

I would like this feature!

**Comment by rzach** [comment] 2020-07-19 17:02
I added request for support for timestamps etc. to issue #85

**Comment by loighic** [comment] 2020-08-09 22:24
I'm curious how the treatment of late problems might work. Carnap kind of invites students to do what they can on an assignment, leave, come back, etc., etc. And, of course, as they do so, they are continually getting an updated score for the assignment. Hence, it's not unusual for my students to score, say, a 6/10 on the due date, and then, at some later time (or  times), complete the assignment. 

Applying a penalty to the entire assignment could, at least in principle, mean that by completing it, the student's score ends up being lower than 6/10. 

Alternatively, and, perhaps more equitably, each individual late problem could be penalized. 

(So, if a student had a 6/10 on the due date, she could complete a two-point problem a week late and get partial credit for that problem. Then, she could complete the other two-point problem even later and either get the same partial credit, some lesser amount of partial credit, or maybe no credit, but that wouldn't affect the points that she's already earned.)

**Comment by gleachkr** [comment] 2020-09-01 21:07
I think per-problem will be the way to go. This is how things are handled right now, so it's not any extra work to do things that way, and as @loighic points out, it seems more equitable to do things that way.

**Comment by gleachkr** [comment] 2020-09-09 16:17
This is now implemented - custom late credit can be configured by setting the option `late-credit=N`. Just need to update documentation...

**Comment by rzach** [comment] 2020-09-09 16:22
Does it show if a problem was late or just silently score it differently?

**Comment by gleachkr** [comment] 2020-09-09 16:24
There should be an indicator in the review area that shows that the problem is late - but were you thinking somewhere else, like on the student page?

**Comment by gleachkr** [comment] 2020-09-09 16:33
Documentation updated! I'll go ahead and close this. Maybe we could open another issue for late submission indicators on student pages.

**Closed as completed by gleachkr** 2020-09-09 16:33 UTC

**Comment by rzach** [comment] 2020-09-09 16:35
It's part of issue 85. I was thinking timestamps in the student submitted problems view, and if/when per-problem downloads are possible, in the CSV.

**Comment by loighic** [comment] 2020-09-11 15:31
I was just testing this out, and I gather that the late credit has to be a whole number. I can definitely work with that, although if it was easy to change it so that we could use one or two places after the decimal point, I would suggest that change. 

Typically, I put five problems worth 2 points each on an assignment. Before I tested it out, I was planning to use this: points="2" late-credit="1.4". (So, an entirely late assignment would yield 7/10.) Obviously, I can change the points for each problem and get the same effect with whole numbers, but I would imagine that a 10 or 20 point scale with fractions of a point being part of the late credit is what a lot of people do---although maybe I'm wrong about that.  

But again, if this isn't an easy change to make, I can definitely work with the way it is set now.

**Comment by gleachkr** [comment] 2020-09-11 15:53
@loighic, I'm afraid that'd be kind of hard - there are some assumptions built in to the way that points are handled in a lot of different places that would need to be changed to get fractional points. So maybe it's best to stick with integers for now, if that's OK.

**Comment by loighic** [comment] 2020-09-11 16:02
Ok, sure. Thanks.

**Comment by rzach** [comment] 2020-09-11 16:02
I'd recommend just doubling the value of every question or whatever. So instead of 1 and .5 points you'd have 2 and 1 point.

**Comment by loighic** [comment] 2020-09-11 16:05
Well, I settled on 70 percent credit as the score for a completely late assignment, and so, if I stick with that, I'll have to go to 10 points per problem (and 100 points for an assignment), but that's easy enough to do---next semester.

**Comment by dsanson** [comment] 2020-09-11 16:25
One related feature that would be nice: a way to set the default points for problems course-wide. I can't tell you how many times I've failed to enter in my intended default (10 points), and so posted an assignment with the wrong point values!

More generally, I am startled by my inability to create assignments without making bone-headed mistakes! Makes me wonder if there are features that could be added to Carnap to protect me from myself. Course wide defaults is one example, since it means one less thing to remember every time I create an assignment.

I also make a lot of mistakes when creating problems. If I'm tired, I'll create derivations that are impossible to complete, for example. Or I'll tweak a translation problem, but forget to tweak the scheme of abbreviation. Or I'll create a multiple choice question but forget to mark *any* option as correct! 

Another common one: I screw up line-breaks within an exercise, causing Carnap to parse one problem as two, or just causing it choke altogether.

Maybe Carnap could flag obviously impossible derivations, or multiple choice questions with no correct answers, by turning the box red or something like that. That would help me catch that error before publishing the assignment. I dunno.

Getting Carnap to check whether the scheme of abbreviation contains all the letters needed to answer a translation problems would be more complicated, since right now it's not even aware of the scheme of abbreviation.

I've also thought about the possibility of supporting more standardized formats for entering exercises. I can imagine a YAML format that would be a bit more verbose, but would allow me to leverage existing templating and syntax checking tools in my editor. (I don't know how many Carnap instructors are using a real(TM) editor. So I don't know how many would benefit from this.) A standard format might also be more portable, allowing for easier implementations of question banks, or tools for importing existing questions written for LMS tools.

Could be that the best solution would be to implement a separate tool that translates questions in a YAML format into Carnap's format.

David

**Comment by loighic** [comment] 2020-09-11 17:39
I agree that having Carnap verify that a derivation is possible would be useful. Maybe I'm more paranoid about leaving out a `~` than I should be, and I do most of the derivations in the Manage Uploaded Documents section before I post them, but having Carnap verify that an argument is valid would simplify the process of preparing an assignment. (Or, at least, lessen my paranoia.)
